server {
    listen 80;
    root /usr/share/nginx/html;
    index demo.html;

    location /v1/ {
        proxy_pass http://app-widget:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "no-cache";
    }
}
